import path from 'path';
import fs from 'fs';
import { describe, it, expect } from 'vitest';
import { openapiToTsJsonSchema } from '../src';

const fixtures = path.resolve(__dirname, 'fixtures');

describe('"outputPath" option', async () => {
  it('saves generated schemas to provided path', async () => {
    const customOutputPath = path.resolve(
      fixtures,
      'schemas-autogenerated-custom',
      'custom-path',
    );

    const { outputPath } = await openapiToTsJsonSchema({
      openApiSchema: path.resolve(fixtures, 'mini-referenced/specs.yaml'),
      definitionPathsToGenerateFrom: ['components.schemas'],
      outputPath: customOutputPath,
      silent: false,
    });

    expect(outputPath).toBe(customOutputPath);

    const expectedGeneratedSchemaPath = path.resolve(
      outputPath,
      'components/schemas',
      'Answer.ts',
    );
    expect(fs.existsSync(expectedGeneratedSchemaPath)).toBe(true);
  });
});
