import path from 'path';
import { fixtures } from './fixtures';

/**
 * Generate output paths in the fixtures folder
 * as a schemas-autogenerated-* folder
 */
export function makeTestOutputPath(id: string): string {
  return path.resolve(fixtures, `schemas-autogenerated-${id}-${Date.now()}`);
}
