import path from 'path';

import { testTempPath } from './paths';

/**
 * Generate output paths in test-temp folder
 */
export function makeTestOutputPath(id: string): string {
  return path.resolve(
    testTempPath,
    `schemas-autogenerated-${id}-${Date.now()}`,
  );
}
