version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      fastify:
        patterns:
          - 'fastify'
          - '@fastify/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      upload-download-artifact:
        patterns:
          - 'actions/upload-artifact'
          - 'actions/download-artifact'
