import fs from 'fs/promises';
import path from 'path';

import glob from 'tiny-glob';
import { afterAll } from 'vitest';

const testFolder = path.resolve(__dirname, 'test');
const schemasAutogeneratedGlob = testFolder + '/**/schemas-autogenerated*';

export async function clearGeneratedFiles() {
  const tempFolders = await glob(schemasAutogeneratedGlob, { absolute: true });
  for (const tempFolder of tempFolders) {
    await fs.rm(tempFolder, { recursive: true, force: true });
  }
}

afterAll(async () => {
  await clearGeneratedFiles();
});
