import { readdir, rm } from 'node:fs/promises';
import path from 'node:path';

import { afterAll } from 'vitest';

import { testTempPath } from './test/test-utils';

/**
 * Delete temporary files generated by tests
 * Removing "test/test-temp" seems to cause issues after test execution
 */
export async function clearGeneratedFiles() {
  let files: string[] = [];

  try {
    files = await readdir(testTempPath);
  } catch (error) {
    return;
  }

  for (const file of files) {
    await rm(path.join(testTempPath, file), {
      recursive: true,
      force: true,
    });
  }
}

afterAll(async () => {
  await clearGeneratedFiles();
});
