import path from 'path';
import fs from 'fs/promises';
import { describe, it, expect } from 'vitest';
import { openapiToTsJsonSchema, fastifyIntegrationPlugin } from '../../../src';
import { fixtures, makeTestOutputPath } from '../../test-utils';
import { formatTypeScript } from '../../../src/utils';

describe('fastifyIntegration plugin', () => {
  it('generates expected file', async () => {
    const { outputPath } = await openapiToTsJsonSchema({
      openApiSchema: path.resolve(fixtures, 'complex/specs.yaml'),
      outputPath: makeTestOutputPath('plugin-fastify'),
      definitionPathsToGenerateFrom: ['components.schemas', 'paths'],
      plugins: [fastifyIntegrationPlugin()],
      silent: true,
    });

    const actualAsText = await fs.readFile(
      path.resolve(outputPath, 'fastify-integration.ts'),
      {
        encoding: 'utf8',
      },
    );

    // @TODO find a better way to assert against generated types
    const expectedAsText = await formatTypeScript(`
      // File autogenerated by "openapi-ts-json-schema". Do not edit :)
      import componentsSchemasAnswer from "./components/schemas/Answer";
      import componentsSchemasJanuary from "./components/schemas/January";
      import componentsSchemasFebruary from "./components/schemas/February";
      import componentsSchemasMarch from "./components/schemas/March";

      const componentsSchemasAnswerWithId = {
        ...componentsSchemasAnswer,
        $id: "/components/schemas/Answer",
      } as const;
      const componentsSchemasJanuaryWithId = {
        ...componentsSchemasJanuary,
        $id: "/components/schemas/January",
      } as const;
      const componentsSchemasFebruaryWithId = {
        ...componentsSchemasFebruary,
        $id: "/components/schemas/February",
      } as const;
      const componentsSchemasMarchWithId = {
        ...componentsSchemasMarch,
        $id: "/components/schemas/March",
      } as const;

      // RefSchemas type: tuple of $ref schema types to enable json-schema-to-ts hydrate $refs via "references" option
      export type RefSchemas = [
        typeof componentsSchemasAnswerWithId,
        typeof componentsSchemasJanuaryWithId,
        typeof componentsSchemasFebruaryWithId,
        typeof componentsSchemasMarchWithId,
      ];

      // schemas: array of JSON schemas to be registered with "fastify.addSchema"
      export const schemas = [
        componentsSchemasAnswerWithId,
        componentsSchemasJanuaryWithId,
        componentsSchemasFebruaryWithId,
        componentsSchemasMarchWithId,
      ]`);

    expect(actualAsText).toBe(expectedAsText);

    const answerSchema = await import(
      path.resolve(outputPath, 'components/schemas/Answer')
    );
    const januarySchema = await import(
      path.resolve(outputPath, 'components/schemas/January')
    );
    const februarySchema = await import(
      path.resolve(outputPath, 'components/schemas/February')
    );
    const marchSchema = await import(
      path.resolve(outputPath, 'components/schemas/March')
    );

    const actual = await import(
      path.resolve(outputPath, 'fastify-integration')
    );

    expect(actual.schemas).toEqual([
      { ...answerSchema.default, $id: '/components/schemas/Answer' },
      { ...januarySchema.default, $id: '/components/schemas/January' },
      { ...februarySchema.default, $id: '/components/schemas/February' },
      { ...marchSchema.default, $id: '/components/schemas/March' },
    ]);
  });

  describe('"schemaFilter" option', () => {
    it('generates expected file', async () => {
      const { outputPath } = await openapiToTsJsonSchema({
        openApiSchema: path.resolve(fixtures, 'complex/specs.yaml'),
        outputPath: makeTestOutputPath('plugin-fastify-schemaFilter-option'),
        definitionPathsToGenerateFrom: ['components.schemas', 'paths'],
        refHandling: { strategy: 'keep' },
        plugins: [
          fastifyIntegrationPlugin({
            schemaFilter: ({ id }) => id.startsWith('/components/schemas'),
          }),
        ],
        silent: true,
      });

      const actual = await import(
        path.resolve(outputPath, 'fastify-integration')
      );

      // $ref schemas
      const answerSchema = await import(
        path.resolve(outputPath, 'components/schemas/Answer')
      );
      const januarySchema = await import(
        path.resolve(outputPath, 'components/schemas/January')
      );
      const februarySchema = await import(
        path.resolve(outputPath, 'components/schemas/February')
      );

      // non-$ref schemas
      const marchSchema = await import(
        path.resolve(outputPath, 'components/schemas/March')
      );

      expect(actual.schemas).toEqual([
        { ...answerSchema.default, $id: '/components/schemas/Answer' },
        { ...januarySchema.default, $id: '/components/schemas/January' },
        { ...februarySchema.default, $id: '/components/schemas/February' },
        { ...marchSchema.default, $id: '/components/schemas/March' },
      ]);
    });
  });
});
