// File autogenerated by "openapi-ts-json-schema". Do not edit :)
import componentsSchemasPet from "./components/schemas/Pet";
import componentsSchemasPets from "./components/schemas/Pets";
import componentsSchemasError from "./components/schemas/Error";
import componentsSchemasOwner from "./components/schemas/Owner";

// RefSchemas type: tuple of $ref schema types to enable json-schema-to-ts hydrate $refs via "references" option
export type RefSchemas = [
  typeof componentsSchemasPet,
  typeof componentsSchemasPets,
  typeof componentsSchemasError,
  typeof componentsSchemasOwner,
];

// schemas: array of JSON schemas to be registered with "fastify.addSchema"
export const schemas = [
  componentsSchemasPet,
  componentsSchemasPets,
  componentsSchemasError,
  componentsSchemasOwner,
];
