// File autogenerated by "openapi-ts-json-schema". Do not edit :)
import { with$id as componentsSchemasPet } from "./components/schemas/Pet.js";
import { with$id as componentsSchemasPets } from "./components/schemas/Pets.js";
import { with$id as componentsSchemasError } from "./components/schemas/Error.js";
import { with$id as componentsSchemasOwner } from "./components/schemas/Owner.js";

// RefSchemas type: tuple of $ref schema types to enable json-schema-to-ts hydrate $refs via "references" option
export type RefSchemas = [
  typeof componentsSchemasPet,
  typeof componentsSchemasPets,
  typeof componentsSchemasError,
  typeof componentsSchemasOwner,
];

// schemas: array of JSON schemas to be registered with "fastify.addSchema"
export const schemas = [
  componentsSchemasPet,
  componentsSchemasPets,
  componentsSchemasError,
  componentsSchemasOwner,
];
