import type { FromSchema, JSONSchema } from 'json-schema-to-ts';

import type { RefSchemas } from './definitions/petstore/schemas-autogenerated/fastify-integration.js';

// Enhance JsonSchema with generated OAS refs
export type FromSchemaWithRefs<Schema extends JSONSchema> = FromSchema<
  Schema,
  { references: RefSchemas }
>;
