import type { JsonSchemaToTsProvider } from '@fastify/type-provider-json-schema-to-ts';
import type { FromSchema, JSONSchema } from 'json-schema-to-ts';

import type { RefSchemas } from './definitions/petstore/schemas-autogenerated/fastify-integration';

// Enhance JsonSchema with generated OAS refs
export type FromSchemaWithRefs<Schema extends JSONSchema> = FromSchema<
  Schema,
  { references: RefSchemas }
>;

// Enhance JsonSchemaToTsProvider with generated OAS refs
export type JsonSchemaToTsProviderWithRefs = JsonSchemaToTsProvider<{
  ValidatorSchemaOptions: {
    references: RefSchemas;
  };
  SerializerSchemaOptions: {
    references: RefSchemas;
  };
}>;
