import { defineCommand } from 'citty';

import { loadConfig } from './loadConfig.js';
import { openapiToTsJsonSchema } from './openapiToTsJsonSchema.js';
import type { ImportExtension, Options, RefHandling } from './types.js';

const REF_HANDLING_VALUES: RefHandling[] = ['import', 'inline', 'keep'];
const IMPORT_EXTENSION_VALUES: ImportExtension[] = ['js', 'ts', 'none'];

const FLAG_ARG_NAMES = [
  'input',
  'collections',
  'single',
  'output',
  'import-extension',
  'ref-handling',
  'silent',
] as const;

const splitList = (value: string): string[] =>
  value
    .split(',')
    .map((entry) => entry.trim())
    .filter((entry) => entry.length > 0);

export const cliCommand = defineCommand({
  meta: {
    name: 'openapi-ts-json-schema',
    description:
      'Generate TypeScript-first JSON schemas from an OpenAPI document.',
  },
  args: {
    config: {
      type: 'string',
      description:
        'Path to a JS/TS config file (default export = Options). When used, no other flags are allowed.',
    },
    input: {
      type: 'string',
      description: 'Path to the OpenAPI document (JSON or YAML).',
    },
    collections: {
      type: 'string',
      description:
        'Comma-separated OpenAPI paths to collections of definitions (e.g. "components.schemas").',
    },
    single: {
      type: 'string',
      description:
        'Comma-separated OpenAPI paths to individual definitions (e.g. "paths./users/{id}").',
    },
    output: {
      type: 'string',
      description:
        'Output directory. Defaults to "<openApiDocument-dir>/schemas-autogenerated".',
    },
    'import-extension': {
      type: 'enum',
      options: IMPORT_EXTENSION_VALUES,
      description: 'Import specifier extension used in generated files.',
    },
    'ref-handling': {
      type: 'enum',
      options: REF_HANDLING_VALUES,
      description: 'Strategy for $ref processing.',
    },
    silent: {
      type: 'boolean',
      description: 'Suppress logging output.',
    },
  } as const,
  async run({ args }) {
    const usedFlagArgs = FLAG_ARG_NAMES.filter(
      (name) => args[name] !== undefined,
    );

    if (args.config && usedFlagArgs.length > 0) {
      throw new Error(
        `[openapi-ts-json-schema] --config cannot be combined with other option flags. Found: ${usedFlagArgs
          .map((name) => `--${name}`)
          .join(', ')}`,
      );
    }

    let options: Options;

    if (args.config) {
      options = await loadConfig(args.config);
    } else {
      if (!args.input) {
        throw new Error(
          '[openapi-ts-json-schema] --input is required (or pass --config).',
        );
      }

      options = {
        openApiDocument: args.input,
        targets: {
          collections: args.collections ? splitList(args.collections) : [],
          single: args.single ? splitList(args.single) : [],
        },
        outputPath: args.output,
        // @ts-expect-error citty's camelCase arg accessors widen enum values; runtime is constrained by IMPORT_EXTENSION_VALUES
        importExtension: args.importExtension,
        // @ts-expect-error citty's camelCase arg accessors widen enum values; runtime is constrained by REF_HANDLING_VALUES
        refHandling: args.refHandling,
        silent: args.silent,
      };
    }

    await openapiToTsJsonSchema(options);
  },
});
