import fs from 'fs/promises';
import { existsSync } from 'fs';
import path from 'path';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import YAML from 'yaml';
import get from 'lodash.get';
import {
  clearFolder,
  makeJsonSchemaFile,
  REF_SYMBOL,
  SchemaPatcher,
  convertOpenApiToJsonSchema,
  convertOpenApiParameters,
  refToPath,
  replaceInlinedRefsWithStringPlaceholder,
  SchemaRecord,
} from './utils';

export async function openapiToTsJsonSchema({
  openApiSchema: openApiSchemaRelative,
  definitionPathsToGenerateFrom,
  schemaPatcher,
  outputPath: providedOutputPath,
  silent,
  experimentalImportRefs = false,
}: {
  openApiSchema: string;
  definitionPathsToGenerateFrom: string[];
  schemaPatcher?: SchemaPatcher;
  outputPath?: string;
  silent?: boolean;
  experimentalImportRefs?: boolean;
}) {
  if (definitionPathsToGenerateFrom.length === 0 && !silent) {
    console.log(
      `[openapi-ts-json-schema] ⚠️ No schemas will be generated since definitionPathsToGenerateFrom option is empty`,
    );
  }

  const openApiSchemaPath = path.resolve(openApiSchemaRelative);
  if (!existsSync(openApiSchemaPath)) {
    throw new Error(
      `Provided OpenAPI definition path doesn't exist: ${openApiSchemaPath}`,
    );
  }

  const outputPath =
    providedOutputPath ??
    path.resolve(path.dirname(openApiSchemaPath), 'schemas-autogenerated');

  await clearFolder(outputPath);

  const openApiSchema = await fs.readFile(openApiSchemaPath, 'utf-8');
  const jsonOpenApiSchema: Record<string, any> = YAML.parse(openApiSchema);
  // Resolve external/remote references (keeping $refs)
  const bundledOpenApiSchema = await $RefParser.bundle(jsonOpenApiSchema);
  const initialJsonSchema = convertOpenApiToJsonSchema(bundledOpenApiSchema);

  // Inline $refs
  const inlinedRefs: SchemaRecord = new Map();

  const dereferencedJsonSchema = await $RefParser.dereference(
    initialJsonSchema,
    {
      dereference: {
        // @ts-expect-error onDereference seems not to be properly typed
        onDereference: (ref, inlinedSchema) => {
          if (experimentalImportRefs) {
            // Mark inlined refs with a "REF_SYMBOL" prop
            inlinedSchema[REF_SYMBOL] = ref;

            const { schemaOutputPath, schemaName } = refToPath({
              ref,
              outputPath,
            });

            // Keep track of inline refs
            inlinedRefs.set(ref, {
              schemaName,
              schemaOutputPath,
              schema: replaceInlinedRefsWithStringPlaceholder(inlinedSchema),
            });
          } else {
            /**
             * Add a $ref comment to each inlined schema with the original ref value. Using:
             * https://github.com/kaelzhang/node-comment-json
             */
            inlinedSchema[Symbol.for('before')] = [
              {
                type: 'LineComment',
                value: ` $ref: "${ref}"`,
              },
            ];
          }
        },
      },
    },
  );

  let jsonSchema = convertOpenApiParameters(dereferencedJsonSchema);

  if (experimentalImportRefs) {
    // Generate JSON schema files for inlined $ref's (experimentalImportRefs option)
    for (const [ref, schemaMeta] of inlinedRefs) {
      const { schema, schemaName, schemaOutputPath } = schemaMeta;
      await makeJsonSchemaFile({
        schema,
        schemaName,
        schemaOutputPath,
        schemaPatcher,
        inlinedRefs,
      });
    }

    // Replace inlined Ref schemas with a string placeholder
    jsonSchema = replaceInlinedRefsWithStringPlaceholder(jsonSchema);
  }

  // Generate user defined schemas
  // @TODO make sure generated inlined schemas don't get overridden bu user requested schemas
  for (const definitionPath of definitionPathsToGenerateFrom) {
    const schemas = get(jsonSchema, definitionPath);
    const schemasOutputPath = path.resolve(outputPath, definitionPath);

    for (const schemaName in schemas) {
      await makeJsonSchemaFile({
        schema: schemas[schemaName],
        schemaName,
        schemaOutputPath: schemasOutputPath,
        schemaPatcher,
        inlinedRefs,
      });
    }
  }

  if (!silent) {
    console.log(
      `[openapi-ts-json-schema] ✅ JSON schema models generated at ${outputPath}`,
    );
  }
  return { outputPath };
}
